[workspace]
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
channels = ["conda-forge", "anaconda"]
name = "25-cpp-homework"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[tasks.vcpkg_init]
cmd = ["python", "./scripts/vcpkg_init.py"]

[tasks.vcpkg_install]
cmd = ["python", "./scripts/vcpkg_install.py"]
depends-on = ["vcpkg_init"]
env.ZIC = 'zic'

[dependencies]
pixi-pycharm = ">=0.0.9,<0.0.10"
ninja = ">=1.13.1,<2"
python = ">=3.14,<3.15"
cmake = ">=3.24,<4.0"

[pypi-dependencies]
pathlib = ">=1.0.1, <2"

[target.linux-64.dependencies]
pkg-config = ">=0.29.2,<0.30"
libtool = ">=2.5.4,<3"
tzdata = ">=2025b,<2026a"
zip = ">=3.0,<4"
unzip = ">=6.0,<7"
automake = ">=1.17,<2"
autoconf = ">=2.72,<3"
autoconf-archive = ">=2021.2.19,<2022"

[target.osx-arm64.dependencies]
pkg-config = ">=0.29.2,<0.30"
libtool = ">=2.5.4,<3"
tzdata = ">=2025b,<2026a"
zip = ">=3.0,<4"
unzip = ">=6.0,<7"
automake = ">=1.17,<2"
autoconf = ">=2.72,<3"
autoconf-archive = ">=2021.2.19,<2022"

[target.osx-64.dependencies]
pkg-config = ">=0.29.2,<0.30"
libtool = ">=2.5.4,<3"
tzdata = ">=2025b,<2026a"
zip = ">=3.0,<4"
unzip = ">=6.0,<7"
automake = ">=1.17,<2"
autoconf = ">=2.72,<3"
autoconf-archive = ">=2021.2.19,<2022"
