[workspace]
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
channels = ["conda-forge"]
name = "25-cpp-homework"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[tasks.vcpkg_init]
cmd = ["python", "./.vcpkg/scripts/vcpkg_init.py"]

[tasks.vcpkg_update]
cmd = ["python", "./.vcpkg/scripts/vcpkg_init.py", "--update"]

[tasks.vcpkg_install]
cmd = ["python", "./.vcpkg/scripts/vcpkg_install.py"]
env.ZIC = 'zic'

[tasks.vcpkg_clean]
cmd = ["python", "./.vcpkg/scripts/vcpkg_clean.py"]

[dependencies]
pixi-pycharm = ">=0.0.9,<0.0.10"
ninja = ">=1.13.1,<2"
python = ">=3.14,<3.15"
cmake = ">=3.30.1,<4.0"
nasm = ">=2.16.1,<2.17"

[pypi-dependencies]
pathlib = ">=1.0.1, <2"
jinja2 = ">=3.1.6, <4"

[target.linux-64.dependencies]
bison = ">=3.8.2,<4"
libtool = ">=2.4,<2.5"
tzdata = ">=2025b,<2026a"
zip = ">=3.0,<4"
unzip = ">=6.0,<7"
automake = ">=1.16,<1.17"
autoconf = ">=2.71,<2.72"

[target.osx-arm64.dependencies]
bison = ">=3.8.2,<4"
libtool = ">=2.4,<2.5"
tzdata = ">=2025b,<2026a"
zip = ">=3.0,<4"
unzip = ">=6.0,<7"
automake = ">=1.16,<1.17"
autoconf = ">=2.71,<2.72"

[target.osx-64.dependencies]
bison = ">=3.8.2,<4"
libtool = ">=2.4,<2.5"
tzdata = ">=2025b,<2026a"
zip = ">=3.0,<4"
unzip = ">=6.0,<7"
automake = ">=1.16,<1.17"
autoconf = ">=2.71,<2.72"

[target.linux-64.host-dependencies]
pkg-config = "*"
autoconf-archive = "*"

[target.osx-arm64.host-dependencies]
pkg-config = "*"
autoconf-archive = "*"

[target.osx-64.host-dependencies]
pkg-config = "*"
autoconf-archive = "*"
