[workspace]
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
channels = ["conda-forge"]
name = "25-cpp-homework"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pixi-pycharm = ">=0.0.9,<0.0.10"
ninja = ">=1.13.1,<2"
python = ">=3.14,<3.15"

[pypi-dependencies]
conan = ">=2.22.2, <3"
